baseURL = "https://example.github.io/"
languageCode = "en-us"
title = "Briana N.C. Chronister, PhD, MS"


[params]
  description = "Personal academic website for Dr. Briana N.C. Chronister, an environmental and spatial epidemiologist."
  author = "Briana N.C. Chronister"
  email = "bnchronister@health.ucsd.edu"
  
  # Social links
  github = "https://github.com/bchronister"
  linkedin = "https://www.linkedin.com/in/brianacortez/"
  scholar = "https://scholar.google.com/citations?user=JayrPfwAAAAJ&hl=en"
  espina = "https://sites.ucsd.edu/espina/"
  orcid = "https://orcid.org/0000-0002-8941-3981"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
